// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200718163036_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Backend.Models.Machine", b =>
                {
                    b.Property<int>("machineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("advancedEnvironmentalConditions")
                        .HasColumnType("bit");

                    b.Property<string>("deviceTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("failsafe")
                        .HasColumnType("bit");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<bool>("insertInto19InchCabinet")
                        .HasColumnType("bit");

                    b.Property<string>("installationPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("motionEnable")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("positionAxisNumber")
                        .HasColumnType("int");

                    b.Property<int>("rotationAxisNumber")
                        .HasColumnType("int");

                    b.Property<bool>("simaticCatalog")
                        .HasColumnType("bit");

                    b.Property<bool>("siplusCatalog")
                        .HasColumnType("bit");

                    b.Property<int>("tempMax")
                        .HasColumnType("int");

                    b.Property<int>("tempMin")
                        .HasColumnType("int");

                    b.Property<bool?>("terminalElement")
                        .HasColumnType("bit");

                    b.HasKey("machineId");

                    b.ToTable("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
